nama = input("nama: ")
ttl = input("TTL: ")
alamat = input("alamat: ")
nomor =input("nomor : ")
Prodi = input("prodi: ")
hobi = input("hobi: ")
print("biodatadiri")
print("nama Lengkap:" + nama)
print("TTL:" + ttl)
print("alamat:" + alamat)
print("No. HP:" + nomor)
print("Hobi:" + hobi)
